# Generated by Django 4.2.3 on 2023-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='City_image/')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Qishloq_xojaligi_loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='upload_to/qishloq_xojaligi_loyiha/')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('Tugallangan', 'Tugallangan'), ('Tugallanmagan', 'Tugallanmagan')], default='Tugallanmagan', max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Region_image/')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sanoat_loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='upload_to/sanoat_loyiha/')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('Tugallangan', 'Tugallangan'), ('Tugallanmagan', 'Tugallanmagan')], default='Tugallanmagan', max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Xizmat_korsatish_loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='upload_to/xizmat_korsatish_loyiha/')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('Tugallangan', 'Tugallangan'), ('Tugallanmagan', 'Tugallanmagan')], default='Tugallanmagan', max_length=155)),
            ],
        ),
    ]
